# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/crowe-GL-loader',
                'doc_host': 'https://claude-guan.github.io',
                'git_url': 'https://github.com/claude-guan/crowe-GL-loader',
                'lib_path': 'crowe_GL_loader'},
  'syms': {'crowe_GL_loader.core': {'crowe_GL_loader.core.foo': ('core.html#foo', 'crowe_GL_loader/core.py')}}}
